name: feki_prtfolio_v2
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0

  flutter_bloc: ^8.1.3
  flutter_glow: ^0.3.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  glassmorphism: ^3.0.0
  google_fonts: ^6.1.0
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  seo: ^0.0.5
  url_launcher: ^6.2.2
  web_smooth_scroll: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/.
    - assets/imgs/.
    - assets/projects/.
